### ISSUE TITLE
Replacement for RDFAlchemy?

### ISSUE THREAD

**Issue by joephayes** [EcoStruxure/OLGA#15]
The RDFAlchemy project's repo is archived and inactive - https://github.com/gjhiggins/RDFAlchemy and it doesn't look like there is a clear replacement. Perhaps https://github.com/cosminbasca/surfrdf or https://pypi.org/project/Owlready2/ ?

**Comment by charbull** [comment]
Hi Joe,

I used RDFLib recently.
Please take a look: https://github.com/RDFLib/rdflib

**Comment by joephayes** [comment]
Great thank you! Are you planning on opening a PR that replaces RDFAlchemy with RDFLib?

**Comment by charbull** [comment]
Hi I haven't worked on OLGA to replace it yet.

It is not hard, we need to do the  following:

* create similar files class template: [[RDFLIB Class](https://github.com/EcoStruxure/OLGA/blob/master/OLGA/OLGA-Core/src/main/resources/templates/python/rdfalchemy/template_python_classes.ftl)]
* create similar files class template: [[RDFLIB instance]
(https://github.com/EcoStruxure/OLGA/blob/master/OLGA/OLGA-Core/src/main/resources/templates/python/rdfalchemy/template_python_instances.ftl)]
* Update the setup.py
* Update the Generators to add RDFLib One [here](https://github.com/EcoStruxure/OLGA/tree/master/OLGA/OLGA-Core/src/main/java/semanticstore/ontology/library/generator/generators)

**Comment by charbull** [comment]
@joephayes is this still of any interest?

**Comment by joephayes** [comment]
@charbull - Yes it is!

**Comment by charbull** [comment]
@joephayes I am trying to do some refactoring to make it easier to add this.
Take a look at this PR: #22

**Comment by corymosiman12** [comment]
Hi @charbull - I went through and was able to build the Python library.  When I go to import specific things, I am thrown the following:
```
>>> from digitalbuildings.DigitalBuildings.Rdf.Model import EntityType
>>> from digitalbuildings.DigitalBuildings.Rdf.Model import Equipment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/digitalbuildings/DigitalBuildings/Rdf/Model/Equipment.py", line 5, in <module>
    from digitalbuildings.www.google.com.digitalbuildings._0_0_1.EntityType import EntityType
ImportError: No module named www.google.com.digitalbuildings._0_0_1.EntityType
```

I'm not positive if this is a related issue or if will get taken care of when upgraded to RDFLib.  If so, seems like that is making progress and can wait until then - thanks!

**Comment by charbull** [comment]
Hi @corymosiman12, please add `-preserve` option for the code generation since there are similar class names but different IRI there is a clash.

Thanks

**Comment by charbull** [comment]
Had the same error here: https://github.com/EcoStruxure/OLGA/issues/17

Will find some time to fix that.

**Comment by corymosiman12** [comment]
ah ok - will do, thanks!

**Comment by charbull** [comment]
@corymosiman12 I found a bug and for now fixed manually the code generation for Java.
I put a detailed steps here and the generated source code:https://github.com/google/digitalbuildings/tree/master/ontology/rdf/example

**Comment by corymosiman12** [comment]
Thanks!
